import type { ProductInput } from "@/lib/types";

// Catálogo inicial tomado de "Productos Mente Fría · MF-CAT · Septiembre 2026"
// y de "Pasos a seguir en una llamada". Todos los precios en MXN + IVA.
// Esta lista sólo se usa para poblar la base la primera vez; después todo se
// administra desde /admin/productos.

const SATISFACTION =
  "Garantía de satisfacción de 30 días: si en los primeros 30 días no está satisfecho, se retira el equipo y se reembolsa el 100%.";

const base = {
  currency: "MXN",
  images: [] as string[],
  faqs: [] as { q: string; a: string }[],
  objections: [] as { objection: string; response: string }[],
  active: true,
};

const rigidCommon = {
  category: "Tinas rígidas",
  stock_status: "backorder" as const,
  delivery_time: "10–12 semanas",
  stock_notes:
    "Depende del stock en CDMX al momento de la compra. A veces hay stock y sale pronto; si no, la fecha depende de cuándo llegue. Revisar antes de cada llamada.",
  shipping_cost: 6000,
  installation_requirements: "No requiere obra ni plomería.",
};

const portableCommon = {
  category: "Tinas portátiles",
  stock_status: "in_stock" as const,
  delivery_time: "2–3 días hábiles después del pago",
  stock_notes: "Siempre disponible.",
  shipping_cost: 1500,
  installation_requirements:
    "No aplica: se instala en cinco minutos, sin hielo ni herramientas, en interior o exterior.",
  warranty: `6 meses. ${SATISFACTION}`,
};

const saunaCommon = {
  category: "Saunas",
  stock_status: "backorder" as const,
  delivery_time: "12 semanas",
  stock_notes: "Tiempo sujeto a stock en CDMX al momento de la compra.",
  shipping_cost: 12000,
  segment: "both" as const,
  installation_requirements:
    "La instala un técnico de Mente Fría; el costo depende de la ubicación. Conexión eléctrica 240 V.",
  price_notes: "Anticipo de 50%. Instalación con costo según ubicación.",
};

export const SEED_PRODUCTS: ProductInput[] = [
  // ------------------------------------------------------------------ Rígidas
  {
    ...base,
    ...rigidCommon,
    slug: "mf-one",
    name: "MF ONE",
    description:
      "Tina rígida horizontal de acrílico y fibra de vidrio con chiller de 1 HP integrado. Enfría a 1 °C y calienta a 40 °C. Sin obra ni plomería.",
    price: 169000,
    price_notes:
      "Anticipo de 40%. Envío $6,000. Concesiones autorizadas sólo si el cliente duda mucho y paga esta semana: envío gratis ($6,000) + ProDeck ($6,900) = ahorro de $12,900. Si vive en CDMX o a menos de 2 horas: instalación en casa sin costo.",
    segment: "both",
    features: [
      "Chiller de 1 HP integrado (enfriamiento 3,500 W / calefacción 1,000 W)",
      "Enfría a 1 °C y calienta a 40 °C",
      "Filtro de 20 micras + prefiltro y ozono",
      "WiFi + app y pantalla TFT de 5\"",
      "Acrílico y fibra de vidrio, rígida (no inflable)",
      "Colores negro obsidiana o blanco alpina",
    ],
    benefits: [
      "Agua fría o caliente todo el año sin hielo",
      "No requiere obra ni plomería",
      "Uso residencial y comercial",
      "Estética premium para casa, spa o gimnasio",
    ],
    specs: {
      Dimensiones: "195 × 80 × 71 cm",
      Material: "Acrílico y fibra de vidrio",
      Formato: "Horizontal",
      Capacidad: "400 L interior / 500 L máx.",
      Temperatura: "1 a 40 °C",
      Alimentación: "100–120 V, 60 Hz, 12 A máx., 1,190 W",
      Filtración: "Filtro 20 micras + prefiltro, ozono",
      Control: "WiFi + app, pantalla TFT 5\"",
    },
    ideal_use: "Uso diario residencial premium o comercial (spa, gimnasio, hotel).",
    recommended_customer:
      "Cliente que quiere una tina rígida, no inflable, que también caliente, con ozono, y que valora diseño y durabilidad.",
    warranty: `1 año. Garantía extendida: +12 meses por $13,000. ${SATISFACTION}`,
    sort_order: 10,
  },
  {
    ...base,
    ...rigidCommon,
    slug: "mf-two",
    name: "MF Two",
    description:
      "Tina rígida horizontal de acrílico y fibra de vidrio con Motor Premium externo de 1 HP. Enfría a 1 °C y calienta a 40 °C.",
    price: 144000,
    price_notes: "Anticipo de 40%. Envío $6,000.",
    segment: "residential",
    features: [
      "Motor Premium externo de 1 HP (61.9 × 40.2 × 47.5 cm, 41.5 kg)",
      "Enfriamiento 2,600 W / calefacción 3,416 W",
      "Filtro de papel plisado de 20 micras, ozono integrado, bomba 120 W (1.5 m³/h)",
      "Panel y app Smart Life",
      "Colores blanco o negro",
    ],
    benefits: ["Tina rígida con frío y calor a menor precio que la MF ONE"],
    specs: {
      Dimensiones: "169.2 × 80 × 66 cm",
      Material: "Acrílico y fibra de vidrio",
      Formato: "Horizontal",
      Capacidad: "Aprox. 397 L",
      Temperatura: "1 a 40 °C",
      Alimentación: "106–127 V, 60 Hz, 1,150 W; 9 A nominal, 12.8 A máx.; circuito dedicado de 20 A con tierra",
    },
    ideal_use: "Residencial.",
    recommended_customer: "Cliente residencial que quiere tina rígida con frío y calor.",
    installation_requirements:
      "Sin obra. El motor va en interior con ventilación al exterior, piso firme y nivelado, sin sol directo ni lluvia. Espacio libre: 100 cm arriba y frente al ventilador, 50 cm del serpentín, 20 cm a los lados. Circuito dedicado de 20 A con tierra.",
    warranty: `6 meses. Garantía extendida: +18 meses por $13,000. ${SATISFACTION}`,
    sort_order: 20,
  },
  {
    ...base,
    ...rigidCommon,
    slug: "mf-steel-barrel",
    name: "MF Steel Barrel",
    description:
      "Tina vertical de acero inoxidable con barandales y chiller de 1 HP integrado. 110 cm de profundidad interior. Uso comercial.",
    price: 169000,
    price_notes: "Anticipo de 40%. Envío $6,000.",
    segment: "commercial",
    features: [
      "Chiller de 1 HP integrado (3,500 W / 1,000 W)",
      "Vertical, con barandales; 110 cm de profundidad interior",
      "Filtro de 20 micras y ozono",
      "WiFi + app",
    ],
    benefits: ["Inmersión de pie, muy resistente para alto tráfico"],
    specs: {
      Dimensiones: "120 × 90 × 126 cm (180 cm con barandales)",
      Material: "Acero inoxidable",
      Formato: "Vertical",
      Capacidad: "400 L recomendados / 500 L máx.",
      Temperatura: "1 a 40 °C",
      Alimentación: "110 V, 60 Hz, 12 A máx.",
    },
    ideal_use: "Comercial: gimnasios, clubes, centros de recuperación.",
    recommended_customer: "Negocio con alto tráfico que prefiere inmersión vertical en acero.",
    warranty: `1 año. Garantía extendida: +12 meses por $13,000. ${SATISFACTION}`,
    sort_order: 30,
  },
  {
    ...base,
    ...rigidCommon,
    slug: "mf-steel-horizon",
    name: "MF Steel Horizon",
    description:
      "Tina horizontal de acero inoxidable con el mismo Motor Premium externo de 1 HP del MF Two. Enfría a 1 °C y calienta a 40 °C.",
    price: 144000,
    price_notes: "Anticipo de 40%. Envío $6,000.",
    segment: "both",
    features: [
      "Motor Premium externo de 1 HP (igual que MF Two)",
      "Acero inoxidable",
      "Ozono, filtro 20 micras",
    ],
    benefits: ["Durabilidad del acero en formato horizontal"],
    specs: {
      Dimensiones: "150 × 70 × 70 cm",
      Material: "Acero inoxidable",
      Formato: "Horizontal",
      Capacidad: "400 L interior / 500 L máx.",
      Temperatura: "1 a 40 °C",
    },
    ideal_use: "Residencial y comercial.",
    recommended_customer: "Cliente que prefiere acero inoxidable en formato horizontal.",
    installation_requirements:
      "Sin obra. Mismos requisitos del motor que el MF Two (ventilación, piso nivelado, sin sol directo ni lluvia, circuito dedicado de 20 A).",
    warranty: `6 meses. Garantía extendida: +18 meses por $13,000. ${SATISFACTION}`,
    sort_order: 40,
  },
  // ---------------------------------------------------------------- Portátiles
  {
    ...base,
    ...portableCommon,
    slug: "mf-horizon-premium",
    name: "MF Horizon + Motor Premium",
    description:
      "Tina portátil horizontal de drop-stitch grado militar con Motor Premium 2.0 (1 HP): enfría de 3 °C y calienta hasta 42 °C, con ozono.",
    price: 89000,
    price_notes:
      "Pago completo; llega en 2–3 días hábiles. Envío $1,500. Concesión autorizada sólo si el cliente duda mucho y paga esta semana: envío gratis + 10% de descuento.",
    segment: "both",
    features: [
      "Motor Premium 2.0 de 1 HP: enfría y calienta (3 a 42 °C)",
      "Ozono integrado",
      "400 L en 4.5 h / 300 L en 3.6 h (ambiente 28 °C)",
      "Pared aislada con cámara de aire y tapa térmica",
      "WiFi (iOS y Android)",
      "15 kg vacía, portátil",
    ],
    benefits: [
      "Siempre disponible: llega en 2–3 días hábiles",
      "Se instala en cinco minutos, sin obra",
      "Se puede mover",
      "Ideal también para negocios (gimnasio o spa)",
    ],
    specs: {
      Dimensiones: "160 × 70 × 65 cm",
      Material: "Drop-stitch grado militar",
      Formato: "Horizontal (acostada)",
      Capacidad: "400 L recomendados / 550 L máx.",
      Peso: "15 kg (19 kg con empaque)",
      Temperatura: "3 a 42 °C",
      "Consumo motor": "1,150 W",
      "Motor (dimensiones)": "58.5 × 42.5 × 53 cm, 41.5 kg",
    },
    ideal_use: "Casa o negocio que quiere frío y calor sin obra y con entrega inmediata.",
    recommended_customer:
      "Cliente que quiere su tina ya, que la pueda mover, que también caliente o tenga ozono. Opción para clientes comerciales (a ellos no se les cotiza el Motor Pro).",
    sort_order: 50,
  },
  {
    ...base,
    ...portableCommon,
    slug: "mf-horizon-pro",
    name: "MF Horizon + Motor Pro",
    description:
      "Tina portátil horizontal de drop-stitch grado militar con Motor Pro 2.0 (0.8 HP): sólo enfría, hasta 3 °C. Sin ozono.",
    price: 74000,
    price_notes:
      "Pago completo; llega en 2–3 días hábiles. Envío $1,500. Concesión autorizada sólo si el cliente duda mucho y paga esta semana: envío gratis + 10% de descuento. A clientes comerciales NO se les cotiza el Motor Pro.",
    segment: "residential",
    features: [
      "Motor Pro 2.0 de 0.8 HP: sólo enfría (hasta 3 °C)",
      "400 L en 6.6 h / 300 L en 5.2 h (ambiente 28 °C)",
      "Pared aislada con cámara de aire y tapa térmica",
      "WiFi (iOS y Android)",
      "15 kg vacía, portátil",
    ],
    benefits: [
      "La opción de entrada para agua fría sin hielo",
      "Llega en 2–3 días hábiles",
      "Se instala en cinco minutos",
    ],
    specs: {
      Dimensiones: "160 × 70 × 65 cm",
      Material: "Drop-stitch grado militar",
      Capacidad: "400 L recomendados / 550 L máx.",
      Peso: "15 kg (19 kg con empaque)",
      Temperatura: "Enfría hasta 3 °C (no calienta)",
      "Consumo motor": "725 W",
      Ozono: "No",
    },
    ideal_use: "Uso residencial sólo en frío.",
    recommended_customer: "Persona que sólo quiere frío y busca la opción más accesible. Nunca para clientes comerciales.",
    sort_order: 60,
  },
  {
    ...base,
    ...portableCommon,
    slug: "mf-barrel-premium",
    name: "MF Barrel + Motor Premium",
    description:
      "Tina portátil vertical (de pie) de drop-stitch grado militar con Motor Premium 2.0: enfría y calienta (3 a 42 °C), con ozono.",
    price: 84000,
    price_notes: "Envío $1,500. Llega en 2–3 días hábiles.",
    segment: "both",
    features: [
      "Formato vertical (de pie), ocupa poco espacio",
      "Motor Premium 2.0: frío y calor, ozono",
      "Tapa térmica, pared aislada",
      "13 kg vacía",
    ],
    benefits: ["Ideal para espacios reducidos"],
    specs: {
      Dimensiones: "90 cm diámetro × 90 cm",
      Material: "Drop-stitch grado militar",
      Formato: "Vertical (de pie)",
      Capacidad: "350 L recomendados / 500 L máx.",
      Peso: "13 kg (16 kg con empaque)",
      Temperatura: "3 a 42 °C",
    },
    ideal_use: "Espacios pequeños, interior o exterior.",
    recommended_customer: "Cliente con poco espacio que quiere frío y calor.",
    sort_order: 70,
  },
  {
    ...base,
    ...portableCommon,
    slug: "mf-barrel-pro",
    name: "MF Barrel + Motor Pro",
    description:
      "Tina portátil vertical (de pie) de drop-stitch grado militar con Motor Pro 2.0: sólo enfría, hasta 3 °C.",
    price: 69000,
    price_notes: "Envío $1,500. Llega en 2–3 días hábiles. A clientes comerciales NO se les cotiza el Motor Pro.",
    segment: "residential",
    features: ["Formato vertical", "Motor Pro 2.0: sólo frío", "Tapa térmica", "13 kg vacía"],
    benefits: ["La opción más accesible y compacta"],
    specs: {
      Dimensiones: "90 cm diámetro × 90 cm",
      Material: "Drop-stitch grado militar",
      Formato: "Vertical (de pie)",
      Capacidad: "350 L recomendados / 500 L máx.",
      Temperatura: "Enfría hasta 3 °C (no calienta)",
    },
    ideal_use: "Uso residencial, sólo frío, poco espacio.",
    recommended_customer: "Persona con poco espacio y presupuesto ajustado que sólo quiere frío.",
    sort_order: 80,
  },
  // ------------------------------------------------------------------ Motores
  {
    ...base,
    slug: "motor-comercial-2hp",
    name: "Motor Comercial 2 HP",
    category: "Motores sueltos",
    description: "Motor de 2 HP para gyms, spas y hoteles. Enfría de 0 °C y calienta a 40 °C. 300 L de 20 a 3 °C en 2 h.",
    price: 99000,
    price_notes: "Envío $4,000.",
    shipping_cost: 4000,
    delivery_time: "10–12 semanas",
    stock_status: "backorder",
    stock_notes: "",
    segment: "commercial",
    features: ["2 HP; 5.7 kW enfriamiento / 7.5 kW calefacción", "Ozono", "IPX5, 50 dB, opera desde −10 °C", "Mangueras hasta 3 m"],
    benefits: ["Para instalaciones comerciales con alto uso"],
    specs: { Dimensiones: "61.9 × 40.2 × 47.5 cm", Peso: "75 kg", Consumo: "2.04 kW; bomba 120 W", Temperatura: "0 a 40 °C" },
    ideal_use: "Repuesto o instalación comercial existente.",
    recommended_customer: "Gimnasio, spa u hotel con instalación propia.",
    installation_requirements: "No aplica.",
    warranty: "6 meses. Garantía extendida: 10% del precio de lista (+18 meses).",
    sort_order: 90,
  },
  {
    ...base,
    slug: "motor-premium-2",
    name: "Motor Premium 2.0",
    category: "Motores sueltos",
    description: "Motor de 1 HP: enfría y calienta (3 a 42 °C), con ozono. Repuesto o para una instalación que el cliente ya tiene.",
    price: 74900,
    price_notes: "Envío $1,500.",
    shipping_cost: 1500,
    delivery_time: "2–3 días hábiles",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: ["1 HP; 2,700 W / 2,850 W", "Ozono", "R410A, IPX4, WiFi", "Protección contra fugas"],
    benefits: [],
    specs: { Dimensiones: "58.5 × 42.5 × 53 cm", Peso: "41.5 kg", Consumo: "1,150 W" },
    ideal_use: "Repuesto o tina existente.",
    recommended_customer: "Cliente que ya tiene tina.",
    installation_requirements: "No aplica.",
    warranty: "6 meses. Garantía extendida: 10% del precio de lista (+18 meses).",
    sort_order: 100,
  },
  {
    ...base,
    slug: "motor-pro-2",
    name: "Motor Pro 2.0",
    category: "Motores sueltos",
    description: "Motor de 0.8 HP: sólo enfría, hasta 3 °C. Sin ozono.",
    price: 59900,
    price_notes: "Envío $1,500. No se cotiza a clientes comerciales.",
    shipping_cost: 1500,
    delivery_time: "2–3 días hábiles",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "residential",
    features: ["0.8 HP; 2,230 W", "Sólo enfría", "R410A, IPX4, WiFi"],
    benefits: [],
    specs: { Dimensiones: "55 × 42.5 × 53 cm", Peso: "39 kg", Consumo: "725 W" },
    ideal_use: "Repuesto residencial.",
    recommended_customer: "Cliente residencial que ya tiene tina.",
    installation_requirements: "No aplica.",
    warranty: "6 meses. Garantía extendida: 10% del precio de lista (+18 meses).",
    sort_order: 110,
  },
  // ------------------------------------------------------------------- Saunas
  ...(
    [
      ["huum-001", "Mente Fria + HUUM 001 · STEEL Mini 4", 184000, "100 × 110 × 195 cm", "1 persona", "3.5 kW, 60 kg de piedra", "240 V, 20 A"],
      ["huum-003", "Mente Fria + HUUM 003 · DROP 6", 209000, "180 × 150 × 215 cm", "2–3 personas", "6 kW (Red Dot 2015), 55 kg de piedra", "240 V, 30 A"],
      ["huum-005", "Mente Fria + HUUM 005 · DROP 9", 239000, "200 × 200 × 215 cm", "4 cómodas / 5 máx.", "9 kW (Red Dot 2015), 55 kg de piedra", "240 V, 50 A"],
    ] as const
  ).map(([slug, name, price, dims, cap, heater, elec], i) => ({
    ...base,
    ...saunaCommon,
    slug,
    name,
    description: `Sauna en cedro rojo canadiense con calentador y control HUUM fabricados en Estonia, WiFi desde la app (40–110 °C). Capacidad: ${cap}.`,
    price,
    features: [`Calentador ${heater}`, "Control HUUM UKU WiFi, 40–110 °C", "Cedro rojo canadiense"],
    benefits: ["Sauna premium controlable desde el celular"],
    specs: { "Dimensiones (ancho × fondo × alto)": dims, Capacidad: cap, Calentador: heater, "Conexión eléctrica": elec, Material: "Cedro rojo canadiense" },
    ideal_use: "Casa premium, spa, hotel o centro wellness.",
    recommended_customer: "Cliente que busca la mejor sauna y valora control WiFi y diseño.",
    warranty:
      "3 años en uso residencial y 1 año en uso comercial, en madera, estructura y equipo. HUUM no cubre piedras, resistencias, sensores ni consumibles. " +
      SATISFACTION,
    sort_order: 200 + i * 10,
  })),
  ...(
    [
      ["essentials-001", "Mente Fria Essentials 001 · Harvia Vega", 98000, "100 × 110 × 195 cm", "1 persona", "3.5 kW, 12 kg de piedra"],
      ["essentials-003", "Mente Fria Essentials 003 · Harvia Vega", 129000, "180 × 150 × 215 cm", "2–3 personas", "6 kW, 20 kg de piedra"],
      ["essentials-005", "Mente Fria Essentials 005 · Harvia Vega", 158000, "200 × 200 × 215 cm", "4–5 personas", "9 kW, 20 kg de piedra"],
    ] as const
  ).map(([slug, name, price, dims, cap, heater], i) => ({
    ...base,
    ...saunaCommon,
    slug,
    name,
    description: `Sauna en Canadian Hemlock con calentador Harvia Vega de acero inoxidable y control local (uso de referencia ~70 °C). Capacidad: ${cap}.`,
    price,
    features: [`Calentador Harvia Vega ${heater}`, "Control local", "Canadian Hemlock"],
    benefits: ["Sauna de calidad a precio de entrada"],
    specs: { "Dimensiones (ancho × fondo × alto)": dims, Capacidad: cap, Calentador: heater, "Conexión eléctrica": "240 V", Material: "Canadian Hemlock" },
    ideal_use: "Casa o negocio que busca sauna con mejor precio.",
    recommended_customer: "Cliente sensible al precio que quiere sauna.",
    warranty: `Calentador Harvia 1 año; cabina 1 año en madera y estructura por defectos de fabricación. ${SATISFACTION}`,
    sort_order: 300 + i * 10,
  })),
  // ------------------------------------------------------ Servicios y extras
  {
    ...base,
    slug: "prodeck",
    name: "ProDeck",
    category: "Accesorios",
    description: "Plataforma de acceso antiderrapante, blanca o negra.",
    price: 6900,
    price_notes: "Envío gratis.",
    shipping_cost: 0,
    delivery_time: "",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: ["Antiderrapante", "Blanca o negra"],
    benefits: [],
    specs: {},
    ideal_use: "Acceso cómodo a la tina.",
    recommended_customer: "",
    installation_requirements: "",
    warranty: "",
    sort_order: 400,
  },
  {
    ...base,
    slug: "garantia-extendida",
    name: "Garantía extendida",
    category: "Servicios",
    description:
      "Lleva cualquier tina o motor a 24 meses en total. No se descuenta y lleva IVA. Tinas fijas: $13,000 por unidad (+12 meses en MF ONE y Steel Barrel; +18 en MF Two y Steel Horizon). Portátiles y motores sueltos: 10% del precio de lista ($5,990 a $11,400), +18 meses.",
    price: 13000,
    price_notes: "Tinas fijas $13,000; portátiles y motores 10% del precio de lista. No se descuenta.",
    shipping_cost: null,
    delivery_time: "",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: [],
    benefits: [],
    specs: {},
    ideal_use: "",
    recommended_customer: "",
    installation_requirements: "",
    warranty: "",
    sort_order: 410,
  },
  {
    ...base,
    slug: "filtros-mf-one",
    name: "Filtros MF ONE (paquete de 3)",
    category: "Accesorios",
    description: "Filtro corto y ancho para MF ONE.",
    price: 750,
    price_notes: "Envío $200.",
    shipping_cost: 200,
    delivery_time: "",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: [],
    benefits: [],
    specs: {},
    ideal_use: "",
    recommended_customer: "",
    installation_requirements: "",
    warranty: "",
    sort_order: 420,
  },
  {
    ...base,
    slug: "filtros-motor-2",
    name: "Filtros Motor Pro y Premium 2.0 (paquete de 3)",
    category: "Accesorios",
    description: "Filtro largo, para Horizon y Barrel.",
    price: 490,
    price_notes: "Envío $200.",
    shipping_cost: 200,
    delivery_time: "",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: [],
    benefits: [],
    specs: {},
    ideal_use: "",
    recommended_customer: "",
    installation_requirements: "",
    warranty: "",
    sort_order: 430,
  },
  {
    ...base,
    slug: "tapete-mente-fria",
    name: "Tapete Mente Fría",
    category: "Accesorios",
    description: "Tapete de bienvenida con logo; suele darse de regalo.",
    price: 650,
    price_notes: "Envío gratis.",
    shipping_cost: 0,
    delivery_time: "",
    stock_status: "in_stock",
    stock_notes: "",
    segment: "both",
    features: [],
    benefits: [],
    specs: {},
    ideal_use: "",
    recommended_customer: "",
    installation_requirements: "",
    warranty: "",
    sort_order: 440,
  },
];
