import type { ScoringConfig } from "@/lib/types";

// Configuración inicial del score. Editable desde /admin/score.
// Las categorías mapean a los pasos del manual (A–L).

export const SEED_SCORING: ScoringConfig = {
  categories: [
    {
      key: "opening",
      label: "Apertura y rapport",
      short: "Apertura",
      weight: 10,
      description: "Transmite seguridad, establece cómo se llevará la llamada y crea confianza.",
      manualSteps: ["A", "B"],
      criteria: [
        "Saluda por nombre y se presenta como Mente Fría.",
        "Establece la agenda: primero entender, después recomendar (\"Antes de explicarte los productos, me gustaría entender…\").",
        "Pregunta qué le llamó la atención o cómo llegó.",
        "Pregunta quién más participa en la decisión dentro de los primeros 3 minutos.",
        "Usa la información de preparación disponible (canal, mensaje previo) sin mencionar producto si el cliente no lo dijo.",
      ],
    },
    {
      key: "discovery",
      label: "Descubrimiento y perfilamiento",
      short: "Descubrimiento",
      weight: 30,
      description:
        "La categoría más importante: demuestra que entendió al prospecto ANTES de venderle. Calidad, orden y profundidad de las preguntas.",
      manualSteps: ["C", "D", "E", "F"],
      criteria: [
        "Hace mínimo 5 a 7 preguntas antes de explicar o recomendar producto.",
        "Descubre si es para persona o negocio, uso, objetivo, motivación y experiencia previa.",
        "Descubre ubicación, interior/exterior, espacio/medidas, instalación eléctrica y drenaje.",
        "Pregunta si también quiere que caliente (define motor).",
        "Profundiza el problema: por qué ahora, qué ha intentado, cómo le afecta, qué cambiaría.",
        "Pide el resultado deseado: característica más importante y para cuándo lo quiere.",
        "Descubre presupuesto o rango de inversión cuando es pertinente, competidores y nivel de interés.",
        "Pregunta qué modelo vio y cuál le gustó al final de la C, sin explicar producto.",
        "Las preguntas son abiertas, relevantes y adaptadas al tipo de cliente, no un interrogatorio genérico.",
      ],
    },
    {
      key: "listening",
      label: "Escucha activa",
      short: "Escucha",
      weight: 15,
      description: "Escucha, deja hablar al cliente, retoma sus palabras y hace preguntas de seguimiento.",
      manualSteps: ["D", "E"],
      criteria: [
        "Hace preguntas de seguimiento basadas en lo que el cliente acaba de decir.",
        "Retoma las palabras del cliente casi textuales (las usará en la G).",
        "No interrumpe ni monopoliza la conversación (el cliente habla más que el vendedor en el descubrimiento).",
        "Detecta y explora señales: emociones, dudas, información a medias.",
        "No ignora datos importantes que el cliente mencionó.",
      ],
    },
    {
      key: "recommendation",
      label: "Recomendación / producto",
      short: "Producto",
      weight: 15,
      description: "Recomienda el producto correcto con las razones correctas y sin inventar información.",
      manualSteps: ["G", "H"],
      criteria: [
        "Recomienda UN producto principal (y una alternativa sólo si tiene sentido), no todo el catálogo.",
        "Usa la estructura: \"Por lo que me comentas, buscas [necesidad], lo instalarías en [lugar] y para ti es importante [prioridad]. Por eso…\".",
        "Da las tres razones más fuertes según lo que el cliente necesita, sin vaciar la ficha técnica.",
        "El producto recomendado encaja con el perfil real del cliente (calor, espacio, uso comercial, urgencia, presupuesto).",
        "Toda la información que da es correcta según los documentos oficiales; no inventa.",
        "Confirma antes del precio: \"¿Hasta aquí hace sentido todo?\" o \"¿Hay algo importante que no hayamos considerado?\" y se calla.",
      ],
    },
    {
      key: "objections",
      label: "Manejo de objeciones y precio",
      short: "Objeciones",
      weight: 15,
      description: "Da el precio con seguridad y maneja objeciones entendiendo antes de responder.",
      manualSteps: ["I", "J"],
      criteria: [
        "Da el precio claro, sin disculparse ni justificar, y se queda callado después.",
        "No ofrece descuentos, envío, ProDeck ni instalación al dar el precio; los guarda para la J y sólo si el cliente duda mucho.",
        "Ante una objeción: escucha, confirma, pregunta, identifica la objeción real antes de responder.",
        "Responde con lo que el cliente contó en C/D y con información autorizada.",
        "Las concesiones que usa son sólo las autorizadas y condicionadas al pago esta semana.",
        "Vuelve a pedir la decisión (\"Con eso resuelto, ¿avanzamos?\").",
        "Si no surgieron objeciones, evalúa el manejo del precio y la detección de objeciones con la confirmación.",
      ],
    },
    {
      key: "closing",
      label: "Cierre / siguiente paso",
      short: "Cierre",
      weight: 15,
      description: "Termina la llamada con uno de los tres resultados válidos.",
      manualSteps: ["K"],
      criteria: [
        "Pide el pago o anticipo correcto (MF ONE 40%; Horizon pago completo; saunas 50%).",
        "Si no hay pago: siguiente paso con fecha y hora concretas, con todos los que deciden.",
        "La fecha la propone el vendedor; nunca pregunta \"¿cuándo te marco?\".",
        "\"Te mando la cotización\" sin fecha NO es cierre.",
        "Si el cliente no califica, lo descarta con claridad.",
      ],
    },
  ],
  rules: [
    { id: "early_recommendation", description: "Explicó o recomendó producto antes de hacer al menos 5 preguntas de descubrimiento.", category: "discovery", penalty: 6, active: true },
    { id: "no_decision_maker", description: "No preguntó quién más participa en la decisión (idealmente en los primeros 3 minutos).", category: "opening", penalty: 3, active: true },
    { id: "price_apology", description: "Se disculpó o justificó al dar el precio (\"está un poco caro\", \"sé que es mucho dinero\", \"a lo mejor se sale de tu presupuesto\").", category: "objections", penalty: 4, active: true },
    { id: "talked_after_price", description: "Siguió hablando o agregó cosas inmediatamente después de dar el precio en lugar de quedarse callado.", category: "objections", penalty: 3, active: true },
    { id: "premature_concession", description: "Ofreció descuento, envío gratis, ProDeck o instalación al dar el precio o sin que el cliente dudara mucho.", category: "objections", penalty: 5, active: true },
    { id: "unauthorized_promise", description: "Inventó información o prometió algo no autorizado (precio, característica, fecha de entrega, descuento o condición que no está en los documentos).", category: "recommendation", penalty: 8, active: true },
    { id: "catalog_dump", description: "Presentó todos los productos o vació la ficha técnica sin contexto.", category: "recommendation", penalty: 4, active: true },
    { id: "motor_pro_b2b", description: "Cotizó o recomendó el Motor Pro a un cliente comercial.", category: "recommendation", penalty: 5, active: true },
    { id: "immediate_rebuttal", description: "Respondió una objeción de inmediato sin entenderla primero (sin confirmar ni preguntar).", category: "objections", penalty: 3, active: true },
    { id: "asked_when_to_call", description: "Preguntó \"¿cuándo te marco?\" en lugar de proponer día y hora.", category: "closing", penalty: 3, active: true },
    { id: "open_ending", description: "Terminó la llamada sin pago, sin siguiente paso con fecha y hora, y sin descartar (llamada abierta).", category: "closing", penalty: 6, active: true },
    { id: "missing_other_decider", description: "Había otro decisor y el siguiente paso no lo incluye con fecha y hora.", category: "closing", penalty: 4, active: true },
  ],
  discovery_fields: [
    { key: "who_for", label: "Para quién es", description: "Persona, familia o negocio.", importance: "critical", appliesTo: "all", exampleQuestion: "¿Lo buscas para ti o para un negocio?" },
    { key: "attraction", label: "Qué le llamó la atención", description: "Cómo llegó y qué le atrajo.", importance: "medium", appliesTo: "all", exampleQuestion: "¿Qué fue lo que te llamó la atención de nuestros productos?" },
    { key: "business_type", label: "Tipo de negocio", description: "Qué negocio es y a quién atiende.", importance: "critical", appliesTo: "commercial", exampleQuestion: "¿Qué tipo de negocio es y a quién atiende?" },
    { key: "use_goal", label: "Uso / objetivo", description: "Para qué lo quiere: recuperación, salud, sueño, servicio nuevo…", importance: "critical", appliesTo: "all", exampleQuestion: "¿Qué te gustaría lograr con el cold plunge?" },
    { key: "motivation", label: "Motivación / por qué ahora", description: "Detonante de la búsqueda.", importance: "high", appliesTo: "all", exampleQuestion: "¿Qué te hizo buscarlo justo ahora?" },
    { key: "problem_impact", label: "Problema e impacto", description: "Cómo le afecta el problema en su día o en su negocio.", importance: "high", appliesTo: "all", exampleQuestion: "¿Cómo te afecta eso en tu día?" },
    { key: "experience", label: "Experiencia previa", description: "Si ya usó cold plunge, hielo o sauna.", importance: "high", appliesTo: "all", exampleQuestion: "¿Ya has utilizado cold plunge anteriormente?" },
    { key: "current_solution", label: "Solución actual", description: "Qué usa o ha intentado hoy.", importance: "medium", appliesTo: "all", exampleQuestion: "¿Actualmente tienes alguna solución similar?" },
    { key: "location", label: "Ubicación", description: "Ciudad y lugar de instalación (casa, terraza, negocio).", importance: "critical", appliesTo: "all", exampleQuestion: "¿En dónde te gustaría instalarlo?" },
    { key: "indoor_outdoor", label: "Interior / exterior", description: "Si va adentro o afuera, con sol o techo.", importance: "high", appliesTo: "all", exampleQuestion: "¿Iría en interior o en exterior?" },
    { key: "space", label: "Espacio / medidas", description: "Espacio disponible, medidas y accesos.", importance: "critical", appliesTo: "all", exampleQuestion: "¿Tienes ya las medidas del espacio donde quieres colocarla?" },
    { key: "electrical", label: "Eléctrico y drenaje", description: "Contacto, circuito, drenaje.", importance: "medium", appliesTo: "all", exampleQuestion: "¿Tienes contacto eléctrico y drenaje cerca de donde iría?" },
    { key: "heating", label: "¿Necesita calor?", description: "Si también quiere que caliente (define motor).", importance: "high", appliesTo: "all", exampleQuestion: "¿También quieres que la tina caliente el agua?" },
    { key: "users_frequency", label: "Usuarios y frecuencia", description: "Cuántas personas y qué tan seguido.", importance: "high", appliesTo: "all", exampleQuestion: "¿Cuántas personas la usarían y qué tan seguido?" },
    { key: "model_interest", label: "Modelo que vio", description: "Qué modelo vio y cuál le gustó.", importance: "medium", appliesTo: "all", exampleQuestion: "¿Viste algún modelo en específico? ¿Cuál te gustó?" },
    { key: "key_feature", label: "Característica más importante", description: "Lo que tiene que tener el equipo para que le funcione perfecto.", importance: "high", appliesTo: "all", exampleQuestion: "¿Cuál es la característica más importante que tiene que tener el equipo?" },
    { key: "timeline", label: "Fecha / urgencia", description: "Para cuándo lo quiere instalado.", importance: "critical", appliesTo: "all", exampleQuestion: "¿Para cuándo te gustaría tenerlo instalado?" },
    { key: "budget", label: "Presupuesto", description: "Rango de inversión contemplado.", importance: "critical", appliesTo: "all", exampleQuestion: "¿Ya tienes un presupuesto destinado para el proyecto?" },
    { key: "decision_makers", label: "Decisor", description: "Quién decide y quién más participa.", importance: "critical", appliesTo: "all", exampleQuestion: "Además de ti, ¿hay alguien más involucrado en la decisión?" },
    { key: "competitors", label: "Competidores", description: "Qué otras opciones está evaluando.", importance: "high", appliesTo: "all", exampleQuestion: "¿Estás viendo otras opciones? ¿Qué te gusta de ellas?" },
    { key: "main_concern", label: "Principal preocupación", description: "La objeción real o miedo principal.", importance: "high", appliesTo: "all", exampleQuestion: "¿Qué es lo que más te preocupa de hacer esta compra?" },
  ],
  coach_notes:
    "El manual de ventas tiene prioridad sobre cualquier lista genérica. No des puntos por amabilidad ni por conocer el producto si el vendedor no entendió al cliente antes de venderle.",
};

